# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppetizersSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppetizersSwiftUI

  target 'AppetizersSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppetizersSwiftUIUITests' do
    # Pods for testing
  end

end
