# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.1,name=iPhone 15', 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K']

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: |
        xcodebuild clean build -project AppetizersSwiftUI/AppetizersSwiftUI.xcodeproj -scheme AppetizersSwiftUI/AppetizersSwiftUI -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
       destination: ${{ matrix.destination }}
      
    - name: Test
      run: |
        xcodebuild clean test -project AppetizersSwiftUI/AppetizersSwiftUI.xcodeproj -scheme AppetizersSwiftUI/AppetizersSwiftUITests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
       destination: ${{ matrix.destination }}
